@WebAPI_HostAddress = http://localhost:5000

### 1. Login to get Token
# @name login
POST {{WebAPI_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@demo.com",
  "password": "Admin123!"
}

### 

### 2. Get Servers List
# Note: You need to paste the token from the login response into the Authorization header below
GET {{WebAPI_HostAddress}}/api/v1/servers
Authorization: Bearer YOUR_TOKEN_HERE
Accept: application/json

###

### 3. Get Health Check
GET {{WebAPI_HostAddress}}/health
Accept: application/json
